// <auto-generated />
using System;
using BrotatoServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrotatoServer.Migrations
{
    [DbContext(typeof(BrotatoServerContext))]
    [Migration("20230803194226_Users")]
    partial class Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("BrotatoServer.Models.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CurrentRotation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Run");
                });

            modelBuilder.Entity("BrotatoServer.Models.User", b =>
                {
                    b.Property<ulong>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TwitchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwitchUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SteamId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
