name: Docker

on:
  push:
    branches: [ main, master ]
  
    paths-ignore:
    - 'k8s/**'
  workflow_run:
    workflows: ["Sync"]
    types:
      - completed

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-push:
    name: Build and Deploy to Github Registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${ts}-${sha}" >> $GITHUB_OUTPUT
    
    # These are prerequisites for the docker build step
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Ensure Lowercase Imagename
      run: |
        echo "IMAGE_NAME=${IMAGE_NAME,,}" >> $GITHUB_ENV
    
    - name: Build and publish container image with tag
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: ./BrotatoServer/Dockerfile
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.prep.outputs.BUILD_ID }}